backend:
  name: github
  repo: johndylavina/kim
  branch: main
  auth_scope: repo
  token: $GITHUB_ACCESS_TOKEN
  
media_folder: "images/uploads"  # Where uploaded images go
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "/"
    create: false
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
